### ISSUE TITLE
IMM Review

### ISSUE THREAD

**Issue by idg10** [corvus-dotnet/Corvus.DotLiquidAsync#25]
Go through every item on the IP Maturity Matrix and ensure it is up to date, adding work items in any areas that could be improved

- [x] **Shared Engineering Standards** configured, but on older approach #42
- [x] **Coding Standards** #42
- [x] **Executable Specifications**
- [x] **Code Coverage**
- [x] **Benchmarks** #46
- [x] **Reference Documentation** #47
- [x] **Design & Implementation Documentation** #48
- [x] **How-to Documentation**
- [x] **Date of Last IP Review**
- [x] **Framework Version**
- [x] **Associated Work Items** #49
- [x] **Source Code Availability**
- [x] **License**: Apache 2.0
- [x] **Production Use**
- [x] **Insights** #50
- [x] **Packaging** #51
- [x] **Deployment**
- [x] **Next IMM review** #52 review
